"""
Django settings for medapp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(ei&czih%!g@*4-a0x671qt0zs1pa%$8_xm$!tg(q2tsu%m=%b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_allowed_raw = os.getenv("ALLOWED_HOSTS", "").strip()
if _allowed_raw == "*":
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "backend", "0.0.0.0"]
elif _allowed_raw:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_raw.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'medical',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8100",
    "http://127.0.0.1:8100",
]
# e.g. GCP VM: MEDITAP_CORS_EXTRA_ORIGINS=http://34.12.34.56:8100,https://app.example.com
_cors_extra = os.getenv("MEDITAP_CORS_EXTRA_ORIGINS", "").strip()
if _cors_extra:
    for _o in _cors_extra.split(","):
        _o = _o.strip()
        if _o and _o not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_o)

# Phones / tablets on LAN: open the app as http://<host>:8100
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(:\d+)?$",
    r"^http://127\.0\.0\.1(:\d+)?$",
    r"^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$",
    r"^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$",
    r"^http://172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}(:\d+)?$",
]

# SPA sends this on API calls when staff elevation is active (Tab14).
CORS_ALLOW_HEADERS = (*default_headers, "x-meditap-elevation")

# Django REST Framework global settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "medapp.keycloak_auth.KeycloakAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

# ============================================
# KEYCLOAK (OIDC) — validated in medapp.keycloak_auth
# ============================================
# JWKS: use Docker service hostname from the backend container.
KEYCLOAK_JWKS_URL = os.getenv(
    "KEYCLOAK_JWKS_URL",
    "http://auth:8080/realms/meditap/protocol/openid-connect/certs",
)
# Issuers that may appear in the JWT `iss` claim (browser uses localhost:8081).
_raw_issuers = os.getenv(
    "KEYCLOAK_ALLOWED_ISSUERS",
    "http://localhost:8081/realms/meditap,http://127.0.0.1:8081/realms/meditap,"
    "http://localhost:8080/realms/meditap,http://127.0.0.1:8080/realms/meditap,"
    "http://auth:8080/realms/meditap",
)
KEYCLOAK_ALLOWED_ISSUERS = [s.strip() for s in _raw_issuers.split(",") if s.strip()]
# When DEBUG and KEYCLOAK_TRUST_ISSUER_SUFFIX=true: accept http://<any-host>/… suffix (LAN / mDNS).
KEYCLOAK_ISSUER_SUFFIX = os.getenv("KEYCLOAK_ISSUER_SUFFIX", "/realms/meditap")
KEYCLOAK_TRUST_ISSUER_SUFFIX = DEBUG and os.getenv(
    "KEYCLOAK_TRUST_ISSUER_SUFFIX", ""
).lower() in ("1", "true", "yes")
# Public SPA client id — must match `azp` on access tokens from that client.
KEYCLOAK_EXPECTED_AZP = os.getenv("KEYCLOAK_EXPECTED_AZP", "meditap-spa")
# Optional: add an audience mapper in Keycloak so access tokens include this audience.
KEYCLOAK_AUDIENCE = os.getenv("KEYCLOAK_AUDIENCE", "meditap-backend")
KEYCLOAK_VERIFY_AUDIENCE = os.getenv("KEYCLOAK_VERIFY_AUDIENCE", "").lower() in (
    "1",
    "true",
    "yes",
)

# Staff elevation (patient stays signed in; staff proves identity server-side via password grant).
# Create a confidential Keycloak client with "Direct access grants" ON and map the same
# realm role (e.g. meditap-record-editor) for staff users.
KEYCLOAK_TOKEN_URL = os.getenv(
    "KEYCLOAK_TOKEN_URL",
    "http://auth:8080/realms/meditap/protocol/openid-connect/token",
).strip()
KEYCLOAK_ELEVATE_CLIENT_ID = os.getenv(
    "KEYCLOAK_ELEVATE_CLIENT_ID", "meditap-elevate"
).strip()
KEYCLOAK_ELEVATE_CLIENT_SECRET = os.getenv("KEYCLOAK_ELEVATE_CLIENT_SECRET", "").strip()
MEDITAP_RECORD_EDITOR_ROLE = os.getenv(
    "MEDITAP_RECORD_EDITOR_ROLE", "meditap-record-editor"
).strip()
MEDITAP_ELEVATION_TTL_SECONDS = int(os.getenv("MEDITAP_ELEVATION_TTL_SECONDS", "1800") or "1800")
MEDITAP_ELEVATION_SIGNING_KEY = os.getenv("MEDITAP_ELEVATION_SIGNING_KEY", "").strip()
# Local dev only: master-realm admin password so the API can resolve email → Keycloak
# username before the staff password grant (see medapp.keycloak_dev_user_lookup).
# Matches docker Keycloak defaults when unset; leave empty outside trusted dev machines.
KEYCLOAK_DEV_MASTER_ADMIN_USER = os.getenv(
    "KEYCLOAK_DEV_MASTER_ADMIN_USER", "admin"
).strip()
KEYCLOAK_DEV_MASTER_ADMIN_PASSWORD = os.getenv(
    "KEYCLOAK_DEV_MASTER_ADMIN_PASSWORD", ""
).strip()

# ============================================
# EPIC FHIR (SMART) — optional sandbox read linking
# ============================================
EPIC_INTEGRATION_ENABLED = os.getenv("EPIC_INTEGRATION_ENABLED", "").lower() in (
    "1",
    "true",
    "yes",
)
EPIC_SANDBOX = os.getenv("EPIC_SANDBOX", "true").lower() in ("1", "true", "yes")
EPIC_FHIR_BASE_URL = os.getenv("EPIC_FHIR_BASE_URL", "").strip()
EPIC_AUTHORIZE_URL = os.getenv("EPIC_AUTHORIZE_URL", "").strip()
EPIC_TOKEN_URL = os.getenv("EPIC_TOKEN_URL", "").strip()
EPIC_CLIENT_ID = os.getenv("EPIC_CLIENT_ID", "").strip()
EPIC_CLIENT_SECRET = os.getenv("EPIC_CLIENT_SECRET", "").strip()
EPIC_REDIRECT_URI = os.getenv("EPIC_REDIRECT_URI", "").strip()
EPIC_DEFAULT_SCOPE = os.getenv(
    "EPIC_DEFAULT_SCOPE",
    "openid fhirUser launch/patient patient/Patient.read patient/Observation.read",
).strip()
EPIC_OAUTH_STATE_MAX_AGE = int(os.getenv("EPIC_OAUTH_STATE_MAX_AGE", "600") or "600")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

ROOT_URLCONF = 'medapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medapp.wsgi.application'

from urllib.parse import urlparse

USE_SQLITE = os.getenv("USE_SQLITE", "").lower() in ("1", "true", "yes")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if USE_SQLITE or not DATABASE_URL:
    # Local default: file-based SQLite DB for easy setup.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Basic parser for postgres URLs (docker/prod style).
    url = urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": url.path.lstrip("/"),
            "USER": url.username,
            "PASSWORD": url.password,
            "HOST": url.hostname,
            "PORT": url.port or "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
